version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true # Hot Reload を有効にする
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./frontend:/var/www/frontend" 
