version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/db/mysql_data:/var/www/lib/mysql
    ports:
      - 3336:3306

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && cp -rf /tmp/public/* /app/public/ && mkdir -p tmp/sockets && bundle exec puma -C config/puma.rb"
    volumes:
      - "./backend:/var/www/backend" 
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  web:
    environment:
      TZ: Asia/Tokyo
    build: container/dev-nginx
    volumes:
      - ./container/dev-nginx/log:/var/log/nginx
      - ./backend/public:/backend/public
      - ./backend/tmp:/backend/tmp
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true # Hot Reload を有効にする
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./frontend:/var/www/frontend" 
volumes:
  public-data:
  tmp-data:
  log-data:
